### ISSUE TITLE
Error when using projection containing {fields:1}

### ISSUE THREAD

**Issue by gregbacchus** [kissjs/node-mongoskin#118]
If my document contains an element/subdocument called "fields", I can't include that in a projection, i.e.

`db.test.find({},{fields:1}, ... )` 

causes an error.

**Comment by jmartorell** [comment]
The solution is in #12, where @simenbrekken pointed at the correct syntax:
```javascript
collection.findOne({}, {fields: ['a']}, function(err, item) { ... }
```
