### ISSUE TITLE
Feature Request - MongoSkin to support SSL

### ISSUE THREAD

**Issue by nwkeeley** [kissjs/node-mongoskin#143]
Hi,

I need to connect to my Mongo instance with SSL. Currently I do not see the option to be able to do this with MongoSkin. Are there any plans in the future to implement the ability to connect with SSL or is this something we could add into an upcoming version it would be very helpful.

Thanks

**Comment by jgraham909** [comment]
FYI you can do this mongoskin adds an extra layer of indirection so you have to pass your options in one level lower;

```javascript
var options = {
      'server': {
        ssl: false,           // No SSL
        sslValidate: null,    // Enabled SSL validation
        sslCA: null,          // CA file to use for SSL validation
        sslKey: null,         // Key file to use for SSL authentication
        sslCert: null,        // Cert file to use for SSL authentication
        sslPass: null,        // Password to use for cert/key file
      }
  };
```
