### ISSUE TITLE
Will mongoskin be updated with current mongodb node driver soon?

### ISSUE THREAD

**Issue by bgSosh** [kissjs/node-mongoskin#149]
Mongodb node driver 1.4.4 has bugs which will throw unhandled errors under certain circumstances (e.g.: https://jira.mongodb.org/browse/NODE-210 )

This is causing some problems for us.  Will mongoskin soon be updated to use current node driver soon? (1.4.22)

Thank you

**Comment by guileen** [comment]
Sorry for it. Use peer dependency now, you can  use any version of mongodb.
