### ISSUE TITLE
Is it just me or is mongoskin not neccessary with the latest MongoDB Native JS repository?

### ISSUE THREAD

**Issue by neatcode** [kissjs/node-mongoskin#151]
Is it just me or is mongoskin not neccessary with the latest MongoDB Native JS repository?

The MongoDB Native JS repository is here: https://github.com/mongodb/node-mongodb-native

What does monogoskin add or make simpler that the Native JS repository isn't already doing? I'd like to know before embarking on my project.

I don't want Mongoose because it requires a pre-defined schema and my schemas change.

**Comment by guileen** [comment]
plaease check latest version

**Comment by neatcode** [comment]
I checked the latest version but I don't see how that answers my question.

What does monogoskin add or make simpler that the Native JS repository isn't already doing?
