### ISSUE TITLE
node-mongoskin not maintained anymore?

### ISSUE THREAD

**Issue by gorkem-cetin** [kissjs/node-mongoskin#152]
I see that latest commit is from 8 months ago, which is only an update to readme. There are several issues that were reported, but never answered by Kissjs team.

Are you still maintaining mongoskin?

**Comment by guileen** [comment]
I am sorry that I am not maintaining mongoskin currently, I hope someone can maintain this project.

**Comment by guileen** [comment]
I am sorry that I am not maintaining mongoskin currently, I hope someone can maintain this project.

**Comment by gorkem-cetin** [comment]
Can you write a comment in readme that you are not maintained and looking for a maintainer, because many people think that it's maintained and rely on MongoSkin, while it's not and there are issues connecting mongoskin to MongoDB in some circumstances.

**Comment by guileen** [comment]
Thank you for your advice.
