### ISSUE TITLE
What can we do to help find a maintainer for mongoskin?

### ISSUE THREAD

**Issue by bgSosh** [kissjs/node-mongoskin#157]
For a start, thanks @guileen @fengmk2 for their work on this project.

I'm sure there must many like me, that have come to rely on mongoskin, and are using it in a production capacity, and are now facing the difficult decision of whether or not to remove mongoskin from their projects.  I'd love to keep it, and I wonder if we could do more to try and find someone willing and able to take over the maintenance of the project?  (Unfortunately I'm very short on time, and don't feel that I'm well suited to this).

Perhaps mongodb could update their wiki pages [which list mongoskin] to mention that the project is looking for a maintainer?

Is there anything more we can do?

**Comment by stennie** [comment]
@bgSosh I think likely candidates are those who have [contributed to the project](https://github.com/kissjs/node-mongoskin/graphs/contributors) already (although it looks like you've tagged the two main contributors). You could also try to ping some of those who answer [questions on StackOverflow](http://stackoverflow.com/tags/mongoskin/topusers) or other community forums.

If you've come to rely on mongoskin in production it does sound like you'd at least be motivated enough to be a Collaborator on the project (i.e. helping with issues or reviewing/merging PRs, even if you're short on time).

It would also be worth asking the original maintainer(s) why they chose to look for a new maintainer. Perhaps there are some maintenance challenges (or better alternatives) to consider.

**Comment by stennie** [comment]
@bgSosh Looks at least one new maintainer has been added -- @vkarpov15, who also maintains [Mongoose](http://mongoosejs.com) and works on the MongoDB Node.js driver team.

**Comment by fengmk2** [comment]
ping @vkarpov15

**Comment by vkarpov15** [comment]
Heya - was I ever added to the github repo collaborators list or npm? Happy to maintain but I'd need access first :)

**Comment by fengmk2** [comment]
Hi @vkarpov15 , I had ask @guileen to send you the invitation to join @kissjs/owners group, has any email from github?

/cc @guileen can you add me and @vkarpov15 to @kissjs/owners  again?

**Comment by fengmk2** [comment]
@vkarpov15 npm owner added, sorry for my oblivion.

```bash
$ npm owner ls mongoskin
npm http GET https://registry.npmjs.org/mongoskin
npm http 200 https://registry.npmjs.org/mongoskin
guileen <guileen@gmail.com>
fengmk2 <fengmk2@gmail.com>
vkarpov15 <val@karpov.io>
```

**Comment by fengmk2** [comment]
![image](https://cloud.githubusercontent.com/assets/156269/6775866/35c2a1b4-d172-11e4-8e06-f8fdc2ece8e5.png)

invited again @vkarpov15

**Comment by vkarpov15** [comment]
Got it, thanks. I'll get started on the issue backlog next weekend - mongoose 4 release is my big action item for the week and it's going to be hard to tear my attention away from that.

**Comment by guileen** [comment]
Hi @vkarpov15 , I am so happy that you can join this project, I think it is also a good news for users like @bgSosh .
I think I should remove the "NOT MAINTAINED" note on project page now.

**Comment by vkarpov15** [comment]
That would be great. If you have time, I'd appreciate a quick walkthrough of mongoskin's internals - I've used the module a couple times before but I'm nowhere near as familiar with it as I am with mongoose. Shoot me an email, val [at] karpov [dot] io

**Comment by guileen** [comment]
@vkarpov15 I have send a mail to you, any question is welcome.

**Comment by bgSosh** [comment]
Wow, great outcome!  Thanks @vkarpov15!  Please let me know if there are any tasks which I can assist with.   I'm not familiar with mongoskin internals, but perhaps there's something I can do.

**Comment by quickref** [comment]
Can I expect any updates on mongoskin as mongodb is upgraded to 3.6 now.

Thanks

**Comment by ar2rsawseen** [comment]
Hello,
would like to give a hand at maintaining this library.
We are using it in production, and would not want to give up on it yet, so at least I can maintain main compatibilities for now with native driver, if you are ok with that :)
