### ISSUE TITLE
search by function ?

### ISSUE THREAD

**Issue by Dededede4** [kissjs/node-mongoskin#16]
Hello,
in the terminal mongo this works:

var f = function(){return (this.root.address.test('testRegex') && this.root.name === 'MyName')};
db.my.find(f);

I can not do it on node.js:
var f = function(){return (this.root.address.test('testRegex') && this.root.name === 'MyName')};
db.my.find(f).toArray(feedback); //Cannot call method 'toArray' of undefined

but :
db.my.find().toArray(feedback);  // work

an idea?
thank you !

**Comment by revir** [comment]
well, i found $where works on String, but not function.  
This is a piece of my check function:  

```coffeescript
    _f = ()->return this.version == "#{version}"
    _fs = "this.version == '#{version}'"
    await db['testdb'].find({$where: _f}).sort(date: -1).toArray defer e, packages
    console.log packages
```

I found that it works when i use '_fs',  not when i use '_f'.  

I test it on version '1.3.20' and '1.4.12'.
