### ISSUE TITLE
Cursor option to pre-process results

### ISSUE THREAD

**Issue by paha77** [kissjs/node-mongoskin#161]
Hi,

Is there a way to say to pass a function to the #find method to "pre-process" returned documents?

I'd need to convert the result documents to my own Javascript object instead of having them as a standard Object created fron JSON.

Thank you.

**Comment by vkarpov15** [comment]
Not at the moment. You can always create your own wrapper around `find()`. Or use [mongoose](https://github.com/Automattic/mongoose) :) mongoskin is meant to be more lightweight and so this feature might be overkill.
