### ISSUE TITLE
cannot remove a document

### ISSUE THREAD

**Issue by alexwang2013** [kissjs/node-mongoskin#166]
```javascript
   var ObjectID = req.ObjectID;
    db.collection('prodcuts').remove({_id:ObjectID(productId)}, {safe: true}, function(err, result) {
        console.log(err);
        console.log(result);
        res.send((err === null) ? { msg: '' } : { msg: err });
    });
```
it output err is null, result is 0, but the document in DB cannot be removed.

and i tried the following, it has the same result. but the document in DB cannot be removed.

```
  db.collection('prodcuts').remove({name:'bmw')}, {safe: true}, function(err, result) {
        console.log(err);
        console.log(result);
        res.send((err === null) ? { msg: '' } : { msg: err });
    });
```

anybody could help me for this issue?

Regards

**Comment by vkarpov15** [comment]
Can you run this command in the mongodb shell successfully? That is, does `db.products.remove({ name: 'bmw' });` work?

Also, you may not have noticed but you have a typo in your code, "prodcuts" -> "products"

**Comment by alexwang2013** [comment]
Hi, vkarpov15
Thank you so much. I made a mistake on the spell. it should be "prodcuts" -> "products".
All the statements works fine.
Thank you very much. you solved a problem for me that it took me more than 8 hours :)

Alex
