### ISSUE TITLE
MongoClient.connect doesn't throw error on connection failure

### ISSUE THREAD

**Issue by sincerekamal** [kissjs/node-mongoskin#170]
Hi,
 I'm just trying to connect to MongoDB using MongoSkin's MongoClient.connect(url) when the DB is not running, but it doesn't throw any error. I couldn't able to find any docs for listening to connection failure.

````
var mongo = require('mongoskin');
try {
 var db = mongo.MongoClient.connect(mongo.url)
} catch(e) {
   console.log(e);
}
````

**Comment by matteocontrini** [comment]
Yeah, how can we handle connection errors?

**Comment by vkarpov15** [comment]
[MongoClient.connect() takes a callback](https://github.com/kissjs/node-mongoskin#mongoclientconnect)

**Comment by matteocontrini** [comment]
And what about this syntax? It's not documented.

```js
var mongo = require('mongoskin');
var db = mongo.db(connectionString);
```

**Comment by ghost** [comment]
What's the proper approach/method for this? The callback doesn't have any effect when used:

```
_db = MongoClient.connect(config.mongo, function (err, db) {
    //CHECK ERRORS NEVER CALLED!!!
});
```

Nor do I see anywhere in the source for any `EventEmitter` usages indicating errors, only success/`open`.
