### ISSUE TITLE
MongoDB 3.x auth

### ISSUE THREAD

**Issue by cclient** [kissjs/node-mongoskin#172]
mongoskin version 1.4.1
i used the mongourl to connent mongodb

like this mongodb://usercdp:pass123@10.10.11.222:27017/database

while use mongodb 2.6.6

i can get the data

but if i connent to  mongodb 3.*

notice { [MongoError: auth failed] name: 'MongoError', ok: 0, errmsg: 'auth failed', code: 18 }

i think it may auth in the database whitch setting in url 

then chang url to "mongodb://usercdp:pass123@10.10.11.222:27017/admin"

but fail too;

i hava no idea;

**Comment by cclient** [comment]
i try pkg mongodb get the same issue  
it's mongodb's question

var MongoClient = require('mongodb').MongoClient
MongoClient.connect('mongodb://usercdp:pass123@10.10.11.222:27017/admin', function(err, db) {})
ok
MongoClient.connect('mongodb://usercdp:pass123@10.10.11.222:27017/database', function(err, db) {})
error

**Comment by cclient** [comment]
i use this example solve the problem
https://github.com/hustcer/latino/blob/master/database/database.js

ref from https://github.com/kissjs/node-mongoskin/issues/110

but some different 

mongoskin.db('mongodb://10.10.11.222:27017/test', {
            auto_reconnect : true,
            safe           : true,
            // 可以省略，省略则跟url里面的数据库相同
            username       : 'username',
            password       : 'password'
        })

**Comment by vkarpov15** [comment]
Which version of the mongodb package are you using?

**Comment by cclient** [comment]
mongoskin package auto require mongodb(1.4.38) package

**Comment by mleanos** [comment]
I'm running into a similar issue.. mongoskin is requiring mongodb 1.4.

Any reason to not upgrade to at leat 2.x?

**Comment by vkarpov15** [comment]
Because mongoskin crashes if you use mongodb ~2.0 unfortunately, and I haven't had a chance to fix it.

**Comment by bgSosh** [comment]
Could you clarify whether or not mongoskin currently supports mongo 3 or not please?  Is it just that certain authentication methods are not supported?  Thanks.

**Comment by vkarpov15** [comment]
Should be fine as long as you use 'mongodb' >= 1.4.38, no reason why mongoskin should prevent that AFAIK.

**Comment by cclient** [comment]
now  mongoskin version  2.0.3 solve this issue as it's default ref mongodb version is ~2.0

it is a demo  

var mongoskin=require("mongoskin");
var db=mongoskin.db("mongodb://username:passwd@127.0.0.1:27017/accessdb?authSource=admin");
var col=db.collection("colname");
col.find({}).toArray(function(err,res){
    console.log(res)
})

thanks
