### ISSUE TITLE
How are modules used

### ISSUE THREAD

**Issue by basickarl** [kissjs/node-mongoskin#176]
```
module.helper.toObjectID(hexStr)
```

How is the above implemented.

**Comment by vkarpov15** [comment]
https://github.com/kissjs/node-mongoskin/blob/master/lib/helper.js#L10-L18 . Checks if it's already an object id, and if so, returns it. Then checks for 24 chars and, if so, calls the [mongodb driver's ObjectId contructor](http://mongodb.github.io/node-mongodb-native/2.0/api/ObjectID.html).
