### ISSUE TITLE
Why is mongodb included as a peerDependency?

### ISSUE THREAD

**Issue by bgSosh** [kissjs/node-mongoskin#179]
Seems like it would be more appropriate to include it as a regular dependency.  I've seen some weird npm install/uninstall behaviour related to this.

**Comment by vkarpov15** [comment]
Similar reasons to https://nodejs.org/en/blog/npm/peer-dependencies/ . Things like https://github.com/kissjs/node-mongoskin/blob/master/lib/helper.js won't work quite right if you have mongoskin depending on one version of mongodb and are using another version of mongodb.

**Comment by bgSosh** [comment]
What if someone upgrades the root mongodb installation?  Won't that potentially cause problems for  mongoskin?

**Comment by vkarpov15** [comment]
In theory no, mongoskin is meant to be a much thinner layer on top of the mongodb driver than say mongoose. As a matter of fact, nowadays the features mongoskin provides that the mongodb driver doesn't are pretty limited, mostly just `findById` and a marginally better ObjectId checker, both of which are unlikely to be affected by patch releases.

**Comment by bgSosh** [comment]
Ok.  Thanks for the clarification.
