### ISSUE TITLE
哪位大哥能告诉我这玩意儿咋用呢？

### ISSUE THREAD

**Issue by cuitianze** [kissjs/node-mongoskin#182]
Express官网推荐mongoskin，然而我却找不到正式的文档。。。现在到底现在还有人维护不？

**Comment by vkarpov15** [comment]
Sorry, I can't read Chinese. According to Google translate, I think you're asking whether mongoskin is maintained - the answer is yes, I maintain it. As for the express docs, [I put in a PR to fix that](https://github.com/strongloop/expressjs.com/pull/498)

**Comment by cuitianze** [comment]
Thank you for your answer ! I thought mongoskin is maintained by a chinese company AliPay , so I questioned in Chinese. Sorry for the inconvenience.
