### ISSUE TITLE
How can I call `getIndexes`?

### ISSUE THREAD

**Issue by fresheneesz** [kissjs/node-mongoskin#185]
`mongo.db(url, {journal: true, auto_reconnect:true}).collection('someCollection').getIndexes` doesn't seem to be defined. Where is it?

**Comment by fresheneesz** [comment]
Ok I see that it might be called `listIndexes` in mongo native: https://docs.mongodb.org/v3.0/reference/command/listIndexes/

**Comment by fresheneesz** [comment]
Ok, I can't figure out how to get the results of `getIndexes`. It seems to only return the calling object, no reference to anything that can help me retrieve the results. Whats going on here?

**Comment by vkarpov15** [comment]
`listIndexes()` returns a cursor, so you need to use `toArray()` like shown in usage: https://github.com/kissjs/node-mongoskin#usage

**Comment by fresheneesz** [comment]
@vkarpov15 No, I tried that. It isn't returning a cursor. Please reopen.
